DROP TABLE `additional_options`;--> statement-breakpoint
DROP TABLE `ai_options`;--> statement-breakpoint
DROP TABLE `build_guides`;--> statement-breakpoint
DROP TABLE `builder_profiles`;--> statement-breakpoint
DROP TABLE `car_show_events`;--> statement-breakpoint
DROP TABLE `cars_for_sale`;--> statement-breakpoint
DROP TABLE `color_options`;--> statement-breakpoint
DROP TABLE `companies`;--> statement-breakpoint
DROP TABLE `configurator_bodywork_options`;--> statement-breakpoint
DROP TABLE `configurator_car_models`;--> statement-breakpoint
DROP TABLE `configurator_color_options`;--> statement-breakpoint
DROP TABLE `configurator_customer_configurations`;--> statement-breakpoint
DROP TABLE `configurator_fuel_system_options`;--> statement-breakpoint
DROP TABLE `configurator_glass_options`;--> statement-breakpoint
DROP TABLE `configurator_interior_options`;--> statement-breakpoint
DROP TABLE `configurator_rear_axle_options`;--> statement-breakpoint
DROP TABLE `configurator_suspension_options`;--> statement-breakpoint
DROP TABLE `configurator_wheel_options`;--> statement-breakpoint
DROP TABLE `contact_submissions`;--> statement-breakpoint
DROP TABLE `engine_options`;--> statement-breakpoint
DROP TABLE `engineering_features`;--> statement-breakpoint
DROP TABLE `enhanced_engine_options`;--> statement-breakpoint
DROP TABLE `enhanced_interior_options`;--> statement-breakpoint
DROP TABLE `enhanced_transmission_options`;--> statement-breakpoint
DROP TABLE `enhanced_vehicle_platforms`;--> statement-breakpoint
DROP TABLE `event_comments`;--> statement-breakpoint
DROP TABLE `event_venues`;--> statement-breakpoint
DROP TABLE `gateway_vehicles`;--> statement-breakpoint
DROP TABLE `hero_content`;--> statement-breakpoint
DROP TABLE `interior_options`;--> statement-breakpoint
DROP TABLE `investment_analytics`;--> statement-breakpoint
DROP TABLE `luxury_showcases`;--> statement-breakpoint
DROP TABLE `market_data`;--> statement-breakpoint
DROP TABLE `market_valuations`;--> statement-breakpoint
DROP TABLE `newsletter_subscribers`;--> statement-breakpoint
DROP TABLE `process_steps`;--> statement-breakpoint
DROP TABLE `projects`;--> statement-breakpoint
DROP TABLE `research_articles`;--> statement-breakpoint
DROP TABLE `simple_transmission_options`;--> statement-breakpoint
DROP TABLE `team_members`;--> statement-breakpoint
DROP TABLE `technical_specifications`;--> statement-breakpoint
DROP TABLE `testimonials`;--> statement-breakpoint
DROP TABLE `transmission_options`;--> statement-breakpoint
DROP TABLE `user_configurations`;--> statement-breakpoint
DROP TABLE `user_itineraries`;--> statement-breakpoint
DROP TABLE `user_preferences`;--> statement-breakpoint
DROP TABLE `users`;--> statement-breakpoint
DROP TABLE `vendor_partnerships`;--> statement-breakpoint
DROP TABLE `wheel_options`;